# Generated by Django 2.1.7 on 2020-10-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_userprofile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group_id_list',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rank_id_list',
            field=models.TextField(null=True),
        ),
    ]
