# Generated by Django 2.1.7 on 2020-10-25 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20201023_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rank_id_list',
        ),
    ]
