# Generated by Django 2.1.7 on 2020-11-08 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='talkcommentmodel',
            table='talk_comment',
        ),
        migrations.AlterModelTable(
            name='talkmodel',
            table='talk',
        ),
    ]
