# Generated by Django 2.1.7 on 2020-10-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='entry_code',
            field=models.CharField(max_length=8, unique=True, verbose_name='令牌'),
        ),
    ]
