# Generated by Django 2.1.7 on 2020-10-25 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20201023_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeworkrank',
            old_name='rank_id_list',
            new_name='user_id_list',
        ),
        migrations.AlterField(
            model_name='homeworkrank',
            name='homework',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='homework_by', to='groups.HomeWork'),
        ),
    ]
