# Generated by Django 2.1.7 on 2020-10-25 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20201025_0638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeworkrank',
            name='homework',
        ),
        migrations.DeleteModel(
            name='HomeWorkRank',
        ),
    ]
