# Generated by Django 2.1.7 on 2020-10-26 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20201025_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='al_achieve',
        ),
    ]
